cmake_minimum_required(VERSION 4.00)
project(bybit_api)

set(CMAKE_CXX_STANDARD 20)

if (MSVC)
    add_definitions(-D_WIN32_WINNT=0x0A00 /bigobj /utf-8)
else ()
    add_definitions(-fPIC)
endif ()

if (POLICY CMP0167)
    cmake_policy(SET CMP0167 NEW)
endif ()

find_package(Boost 1.88 REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(ZLIB REQUIRED)
find_package(nlohmann_json CONFIG REQUIRED)
find_package(spdlog CONFIG REQUIRED)
find_package(magic_enum REQUIRED)

include_directories(include SYSTEM ${Boost_INCLUDE_DIR} ${OPENSSL_INCLUDE_DIR})

if (NOT TARGET stonky_common)
    add_subdirectory(stonky-cpp-common)
endif ()

set(HEADERS
        include/stonky/bybit/bybit_models.h
        include/stonky/bybit/bybit.h
        include/stonky/bybit/bybit_rest_client.h
        include/stonky/bybit/bybit_http_session.h
        include/stonky/bybit/bybit_ws_client.h
        include/stonky/bybit/bybit_ws_session.h
        include/stonky/bybit/bybit_ws_stream_manager.h
        include/stonky/bybit/bybit_ws_private_stream_manager.h
        include/stonky/bybit/bybit_event_models.h
        include/stonky/bybit/bybit_execution_gateway.h)

set(SOURCES
        src/bybit.cpp
        src/bybit_models.cpp
        src/bybit_rest_client.cpp
        src/bybit_http_session.cpp
        src/bybit_ws_client.cpp
        src/bybit_ws_session.cpp
        src/bybit_ws_stream_manager.cpp
        src/bybit_ws_private_stream_manager.cpp
        src/bybit_event_models.cpp
        src/bybit_execution_gateway.cpp)

if (MODULE_MANAGER)
    set(MODULE_HEADERS
            include/stonky/bybit/bybit_futures_exchange_connector.h
            include/stonky/bybit/bybit_spot_exchange_connector.h
            include/stonky/bybit/bybit_module.h)

    set(MODULE_SOURCES
            src/bybit_futures_exchange_connector.cpp
            src/bybit_spot_exchange_connector.cpp
            src/bybit_module.cpp)
endif ()

if (MODULE_MANAGER)
    add_library(bybit_api SHARED ${SOURCES} ${HEADERS} ${MODULE_SOURCES} ${MODULE_HEADERS})
else ()
    add_library(bybit_api STATIC ${SOURCES} ${HEADERS})
endif ()

option(ENABLE_TESTS "Build bybit_api test executables" OFF)
if (ENABLE_TESTS)
    add_executable(bybit_test test/main.cpp)
    target_link_libraries(bybit_test PRIVATE spdlog::spdlog_header_only bybit_api)

    add_executable(bybit_benchmark test/benchmark.cpp)
    target_link_libraries(bybit_benchmark PRIVATE spdlog::spdlog_header_only bybit_api)

    add_executable(bybit_exec_probe test/exec_probe.cpp)
    target_link_libraries(bybit_exec_probe PRIVATE spdlog::spdlog_header_only bybit_api)
endif ()

target_link_libraries(bybit_api PRIVATE spdlog::spdlog_header_only OpenSSL::Crypto OpenSSL::SSL ZLIB::ZLIB stonky_common nlohmann_json::nlohmann_json)
